-- Esvaziada: o seed de dev foi movido para apps/backend/scripts/seed/seed.sql
-- (execução manual). Mantida como no-op, não deletada, para preservar a sequência
-- de versões do golang-migrate em bancos que já a aplicaram.
